#######################################################################################
# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: SML Public Methods
author: ONS Statistical Methods Library
#copyright: "2025"                               # Copyright year to be placed in the footer
logo: assets/logo.svg
favicon: assets/favicon.ico

#######################################################################################
# HTML-specific settings
# Add GitHub buttons to book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: false                  
  extra_footer: |                               # Add license info to footer 
    <p>                                         
    License: Documentation - Open Government 3.0 license. SML codebase & sample code in documentation - MIT License.  
    </p>

#######################################################################################
# Information about where the book exists on the web
repository:
  url: https://github.com/ONSDigital/sml-jbook  # Online location of your book
  path_to_book: public_pages                    # Optional path to your book, relative to the repository root
  branch: main                                  # Which branch of the repository should be used when creating links (optional)

#######################################################################################
# Declare primary language to assist screen reader and browser translation tools
sphinx:
  config:
    language: en                                # Declare primary language to assist screen reader and browser translation tools
    html_show_copyright: false

#######################################################################################
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: smluserguides.tex

#######################################################################################
# Execution settings
# See https://jupyterbook.org/content/execute.html
execute:                                      
  execute_notebooks: force                      # Force re-execution of notebooks on each build.

